language: php

sudo: false

php:
  - 7.4

env:
  global:
    - COMPOSER_GLOBAL_FLAGS=--no-interaction --prefer-source -o

matrix:
  allow_failures:
    - php: hhvm

install:
  - travis_retry composer update ${COMPOSER_GLOBAL_FLAGS}
  - nvm install
  - npm install

script:
  # Run QA
  - make qa

  # Run Nette Tester
  - make test

after_failure:
  # Print *.actual content
  - 'for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'

cache:
  directories:
    - $HOME/.composer/cache
